### PR TITLE
New post: 2020-02-11: introduction to webscraping with R by Jorge Cimentada

### PR DESCRIPTION
**Pull request by cimentadaj**
Hi,

This is my PR for the talk in February 11 of 2020 on webscraping. Here is the summary of the changes:

* Add 2020-02-11.Rmd in `content/post`
* I have several images and a small csv file for the example which I've placed in `static/post/2020-02-11_files/`

In the `Rmd` file, whenever I refer to the images or the csv file, I link them directly to the static folder to make sure the links correspond to the images. However, when I run `blogdown::serve_site()` the `Rmd` has problems compiling and cannot find the files. To make thing easier to debug, I've marked each line of code where I link to images or the csv file with `# EXT`.

I'm sure it's easier for you to pinpoint what I'm doing wrong. If so, let me know and I'll add some commits to fix it.

### CODE REVIEW

**Comment by Enchufa2** [comment]
> In the `Rmd` file, whenever I refer to the images or the csv file, I link them directly to the static folder to make sure the links correspond to the images. However, when I run `blogdown::serve_site()` the `Rmd` has problems compiling and cannot find the files.

This is because, for blogdown, `static` is the root of the web for static content. So if you have a file under `static/post/xxxx-xx-xx_files/some_path/file.png` that you want to include in your post, just use `/post/xxxx-xx-xx_files/some_path/file.png` as the path, without `static`, and there's no need to use `here`.

Also, I believe that the deployment of the preview on Netlify is failing because this line in the YAML header

```yml
authors: Jorge Cimentada
```

should be instead

```yml
authors: ["Jorge Cimentada"]
```

**Comment by cimentadaj** [comment]
Thanks @Enchufa2. This managed to fix both the compilation problem as well as the image links. However, for reading the `csv` file (which is in the same directory as the `png` images), doesn't work. It says it cannot find the `csv` file for some reason (line 432). I double checked  to make sure the file is there and everything looks like it should work.

**Comment by Enchufa2** [comment]
> Thanks @Enchufa2. This managed to fix both the compilation problem as well as the image links. However, for reading the `csv` file (which is in the same directory as the `png` images), doesn't work. It says it cannot find the `csv` file for some reason (line 432). I double checked to make sure the file is there and everything looks like it should work.

It works just for web resources. E.g., any chunk with an image is translated into

```
<img src="/post/...">
```

etc., so that image can be found by the web server. Or if you want to provide a link to the CSV, you need to write

```
you can find the file in [this link](/post/.../file.csv)
```

which is translated into

```
you can find the file in <a href="/post/...file.csv">this link</a>
```

again to be correctly served by the web server. But of course, if you want to read the CSV into the R session, you need to include the full path from the root of the **project**:

```r
res <- read.csv("static/post/2020-02-11_files/school_coordinates.csv")
```

should work. Wrapping up:

- Stuff to be manipulated within the R session: `static/post/.../stuff`
- Stuff to be found by the web server: just `/post/.../stuff`

**Comment by cimentadaj** [comment]
Testing `blogdown::serve_site()` with `res <- read.csv("static/post/2020-02-11_files/school_coordinates.csv")` gives the same error :/

**Comment by Enchufa2** [comment]
You are right. I was mistaken (already corrected in my last message): the path should be **relative to the location of the Rmd**. So this should work:

```r
res <- read.csv("../../static/post/2020-02-11_files/school_coordinates.csv")
```

and yet, it doesn't work either (maybe a bug?). But if you create another directory called e.g. `2020-02-11_data` and move the CSV there, this works (finally!):

```r
res <- read.csv("../../static/post/2020-02-11_data/school_coordinates.csv")
```

or you could just embed the CSV into the chunk (I prefer this solution if you are not providing a link to the CSV, because it's just 28 lines).

Further comments: please

- use `##` (h2) as the top-level header (the title of the post is h1);
- don't hide the chunk that loads all the packages needed;
- put a warning somewhere saying that `scrapex` comes with *more than 400 MB* of external data, just in case. :)

**Comment by cimentadaj** [comment]
Great advice. I've deleted the `csv` file, read it locally within the `Rmd`, included all packages (thanks!), fixed heading sizes and warned about the size of scrapex. Everything should be working now and it's ready for review.

By the way, if you have any strategies on handling the size in `scrapex`, I'd really appreciate it. I tried going for a work around of zipping the data in the repo and unzipping after installation but I'm not sure it's a good idea to increase the size unexpectedly **after** a user downloads the package.

**Comment by Enchufa2** [comment]
About the size, since you store that data for scraping purposes, I would remove every resource that is not an html or a robots.txt file: I see tons of fonts, images, CSS and JS files.

**Comment by cimentadaj** [comment]
Yeah, the thing is I want to examples to be exactly as the website to make them as real as possible. I downloaded all images and files on purpose so that all logos are there, etc.. The idea behind this package is that it can be a curated list of saved examples for scraping purposes in the future.

**Comment by Enchufa2** [comment]
Still, there's *a lot* of duplicated stuff.

**Comment by cimentadaj** [comment]
Ah, I hadn't noticed. I'll check this out.

**Comment by cimentadaj** [comment]
@DavidGarHeredia, gracias por los comentarios. Ya los he revisado.

**Comment by cimentadaj** [comment]
Uff, disculpa @DavidGarHeredia! Pensaba que había corregido todo. Ya debería estar todo listo.

**Comment by Enchufa2** [comment]
¡Merged, gracias! Cuando puedas, nos envías por favor por email la info para programar también el [anuncio](https://codingclubuc3m.rbind.io/talk/2019-11-26/):

- Abstract, o nos dices qué parrafos cogemos del principio del artículo a tal efecto.
- Foto.
- Requirements.
- Bio.

**Pull request merged**
